### YamlMime:FAQ
metadata:
  title: プロダクト キーに関するよく寄せられる質問
  ms.author: cmcatee
  author: cmcatee-MSFT
  manager: scotv
  ms.reviewer:
  - Rani Chegondi
  - Armando Valenzuela
  ms.date: 07/22/2021
  audience: Admin
  ms.topic: article
  ms.service: bookings
  ms.custom: commerce_licensing
  localization_priority: Normal
  description: プロダクト キーに関するよく寄せられる質問
  ms.openlocfilehash: 4ab699c56eaa9c7676104989f14450f4d1f8487a
  ms.sourcegitcommit: d817a3aecb700f7227a05cd165ffa7dbad67b09d
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 07/29/2021
  ms.locfileid: "53656549"
title: プロダクト キーに関するよく寄せられる質問
summary: ''
sections:
- name: 全般
  questions:
  - question: >
      プロダクト キーとは
    answer: >
      プロダクト キーを使用すると、特定のボリューム ライセンス プログラムでライセンスを取得したソフトウェア製品を使用できます。 この製品に記載されているプロダクト Microsoft 365 管理センターボリューム ライセンス製品でのみ使用し、組織でのみ使用することを目的とします。


      Online Service Activation (OSA) キーは、サブスクリプションのアクティブ化に使用される単一Microsoft Online Servicesです。


      詳細については、「Online [Service Activation for Open programs FAQ」を参照してください](/licensing/online-service-activation-faq)。
  - question: >
      製品キーを検索する方法をMicrosoft 365 管理センター?
    answer: "1. アカウントにサインインMicrosoft 365 管理センター。 \n2. [製品の  >  **請求]**  >  **[ボリューム ライセンス]** に移動&キー>をクリックし、[キーの表示]  >  **を選択します**。\n\n各製品のプロダクト キー情報、ライセンスの種類 (ボリューム ライセンス キー、キー管理サービス (KMS)、および複数のライセンス認証キー (MAK))、および使用できる MAK ライセンス認証の数を確認できます。\n\n[ **すべてのプロダクト キーをダウンロードする]** を選択して、ライセンスに表示されるキーをローカル ドライブにダウンロードします。\n"
  - question: >
      プロダクト キーをSQL Serverする方法
    answer: >
      ライセンス SQLは、管理センターに表示されるのではなく、ソフトウェアのライセンス認証ウィザードに埋め込まれているので、インストール中に自動的に検出されます。 詳細については、「[SQL Server インストール ガイド] (/sql/database-engine/install-windows/install-sql-server)」を参照してください。


      また、管理センターから ISO ファイルSQLダウンロードして、キー>できます。\x64 フォルダー> DefaultSetup.iniします。 新しいエディションをインストールまたはアップグレードする前に、既存のバージョンをSQLしてください。 製品のインストールまたはオンライン サービスのライセンス認証中に技術的な問題のトラブルシューティングに関するヘルプが必要な場合は、テクニカル サポート要求を送信して Microsoft テクニカル サポートに [問い合わせください](https://support.microsoft.com/oas)。
  - question: >
      ボリューム ライセンス購入のプロダクト キーを見つける方法
    answer: "契約でキーが必要な製品へのアクセスを承認する場合は、[製品のボリューム ライセンスのダウンロード] &に移動して、それらのキー  >    >    >  **を見つける必要があります**。 \n\nただし、プロダクト キーを必要としない製品があります。 この情報は、[ダウンロードとキー] カタログの製品の説明に記載されています。\n\n製品にキーが必要かどうかを確認するには、[製品のライセンス認証とキー [情報] に移動します](https://licensingapps.microsoft.com/product-activation)。 [製品の検索] で、製品を選択するか、製品名を検索します。\n"
  - question: >
      セットアップ キーとは
    answer: >
      製品/バージョンの組み合わせごとにセットアップ キーを使用して、ライセンス認証をバイパスして製品のロックを解除します。 セットアップ キーは、次の 2 つの方法で取得できます。

        - **物理的なフルフィルメント** 物理的なフルフィルメントによって取得された製品の場合、セットアップ キーはメディア スリーブに印刷されます。
        - **フルフィルメントのダウンロード** 管理センターからダウンロードして取得した製品では、セットアップ キーがダウンロード画面に表示され、次のテキストが表示される場合があります。ダウンロード可能な一部の製品にはセットアップ キーが必要です。 製品のインストール中に必要なセットアップ キーに注意してください。 セットアップ キーの詳細については、「クライアント[セットアップ KMS」を参照してください](/windows-server/get-started/kmsclientkeys)。
  - question: >
      契約に関連付けられているプロダクト キーは何ですか?
    answer: >
      ボリューム ライセンスプロダクト キーは、Microsoft Relationship Summary に記載されている各ライセンス ID [に対して提供されます](/licensing/license-faq)。 このリレーションシップの概要は、ボリューム ライセンス サービス センターにあります。 詳細については [、「What is a Licensing ID」を参照してください](/licensing/license-faq#what-is-a-licensing-id)。 ライセンスの数種類の ID を使用できます。

        - Enterprise Agreement (EA) および Select Plus のお客様は、製品プール (システム、サーバー、およびアプリケーション) ごとにプロダクト キーを受け取ります。
        - [契約のお客様は、購入予測に基づいて製品プール (システム、サーバー、およびアプリケーション) ごとにプロダクト キーを受け取る] を選択します。
        - Open License のお客様と Open Value のお客様は、ライセンス購入に基づいて該当するプロダクト キーを受け取ります。

      詳細については、「ライセンスの概要 [に関するよく寄せられる質問」を参照してください](/licensing/license-faq)。


      **メモ** すべてのお客様は、再イメージングおよびダウングレードの目的でプロダクト キーを使用する権利を持っています。 [プラス]、Enterprise Agreement (EA)、および [顧客のトレーニングとバックアップの評価権限が制限されています] を選択します。 詳細については、「製品ライセンス [ブリーフ」を参照してください](/licensing/learn-more/volume-licensing-briefs)。
- name: ボリューム ライセンス認証
  questions:
  - question: >
      ボリュームライセンス認証とは
    answer: >
      ボリューム ライセンス認証は、ボリューム ライセンス プログラムでライセンスされているオペレーティング システムを実行しているコンピューターでWindowsのライセンス認証プロセスを自動化および管理するのに役立つ構成可能なソリューションです。 ボリューム ライセンス認証は、ボリューム ライセンス契約に基Officeボリューム ライセンス認証をサポートする、Microsoft の他のソフトウェアでも使用されます。 詳しくは、以下を参照してください。
        - [ユーザーのボリューム ライセンス認証を管理Office](/deployoffice/vlactivation/tools-to-manage-volume-activation-of-office)
        - [ユーザーのボリューム ライセンス認証Windows 10](/windows/deployment/volume-activation/volume-activation-windows-10)

      ボリューム ライセンス認証は、ボリューム ライセンス プログラムの対象となるシステムにのみ適用され、ライセンス認証のツールとして厳密に使用されます。 ライセンスの請求や請求には関連付けではありません。


      ボリュームライセンス認証には、ボリュームライセンス認証を完了するための 2 つの方法があります。 お客様が組織のシステムをアクティブ化するには、次のいずれかのキーの種類または両方のキーを使用できます。
        - キー管理サービス (KMS) を使用すると、組織は独自のネットワーク内でシステムをアクティブ化できます。
        - 複数のライセンス認証キー (MAK) は、Microsoft ホスト型ライセンス認証サービスを使用して、一度にシステムをアクティブ化します。
  - question: >
      (キー管理サービス) のKMS?
    answer: >
      KMSは、製品のライセンス認証のために個々のコンピューターが Microsoft に接続する必要がなくなるので、組織が独自のネットワーク内のシステムをアクティブ化できるライセンス認証サービスです。 専用のシステムは不要で、他のサービスを提供するシステムで共同ホストできます。


      KMS環境の物理コンピューターまたは仮想コンピューターの最小数が必要です。 ライセンス認証のしきい値と呼ばれるこれらの最小値は、顧客が簡単に満たEnterpriseされます。

        - ライセンス認証のしきい値Windows
          - サーバーを実行しているサーバーをアクティブ化するには、組織に少なくとも 5 台のコンピューター Windows必要があります。
          - 組織で、クライアント システムをアクティブ化するには、25 台以上のコンピューターが必要です。Windows。
        - ライセンス認証のしきい値Office
          - 組織では、インストール済み製品をライセンス認証するために、Officeエディションを実行Office 5 台以上のコンピューター KMS。

      アクティブ化のしきい値の詳細については、「ボリューム ライセンス認証計画 [ガイド」を参照してください](/windows/deployment/volume-activation/volume-activation-windows-10)。
  - question: >
      ホスト キー KMSは何ですか?
    answer: >
      このKMSは、Microsoft ライセンス認証サーバーを使用して KMS ホスト コンピューターをアクティブ化するために使用され、ホストごとに 10 回のライセンス認証を行う最大 6 KMS ホストをアクティブ化できます。 各KMSホストは、無制限の数のコンピューターをアクティブ化できます。
  - question: >
      オープン ライセンスのお客様KMSにMicrosoft 365 管理センターキーが表示されない理由
    answer: "KMSライセンス認証キー (MAK) を使用する場合、Open 契約に事前割り当てされていないキーは、ライセンス認証の推奨方法です。\n\nKSM キーは、例外として、KMS Server、OS、および Office の最小 KMS Windows ライセンス認証しきい値を満たすユーザーに割り当Office。 例外を要求するには、Web フォーム要求を Microsoft サポートに送信します。\n\n例外を要求するには、VLSC 管理者、キー管理者、またはキー ビューアーのアクセス許可を持ち、次の情報を提供する必要があります。\n  \n  - 契約/登録番号またはライセンス ID と承認。\n  - 製品名 (バージョンとエディションを含む)。\n  - プロダクト キーの最後の 5 文字。\n  - 必要なホストライセンス認証の数。\n  - ビジネスの正当性または展開の理由。\n"
  - question: >
      追加のホストが必要なKMS?
    answer: "6 つ以上のホストKMSアクティブ化するために追加のライセンス認証が必要KMS、サポートに Web フォーム要求をMicrosoft 365 管理センターしてください。 \n\n例外を要求するには、VLSC 管理者、キー管理者、またはキー ビューアーのアクセス許可を持ち、次の情報を提供する必要があります。\n  \n  - 契約/登録番号またはライセンス ID と承認。\n  - 製品名 (バージョンとエディションを含む)。\n  - プロダクト キーの最後の 5 文字。\n  - 必要なホストライセンス認証の数。\n  - ビジネスの正当性または展開の理由。\n"
  - question: >
      複数のライセンス認証キー (MAK) とは何ですか?
    answer: >
      複数ライセンス認証キー (MAK) は、Microsoft ライセンス認証サーバーとの接続を必要とする Microsoft ホスト型ライセンス認証サービスを使用して、一度にシステムをアクティブ化します。 一度コンピューターがライセンス認証されれば、それ以上マイクロソフトと通信する必要はありません。


      **重要** 許可される MAK ライセンス認証の数は、ボリューム ライセンス契約に基づいて行います。
  - question: >
      提供されている MAK ライセンス認証の数が、購入したライセンスの数と一致しない理由
    answer: >
      複数のライセンス認証キー (MAK) KMSを使用することをお勧めします。 KMSは、大規模展開に推奨されるライセンス認証方法です。 多くの要因によって、購入したライセンス、顧客の購入価格レベル、ボリューム ライセンス プログラムなど、各 MAK に関連付けられているライセンス認証の数が決まっています。


      製品で使用可能なライセンス認証の数が、購入したライセンスの数と必ずしも一致するとは限らない。 通常、一部の製品を再インストールしてアクティブ化する必要がある場合に備え、より多くのライセンス認証を受け取る必要があります。 ライセンス数を表示するには、契約の [ライセンスの概要] セクションを確認します。
  - question: >
      MAK ライセンス認証制限の引き上げを要求する方法
    answer: "MAK ライセンス認証数量の増加は、Web フォームを介して要求できます。例外によって付与されます。 カナダと米国の場合は、ボリューム ライセンス [サポート要求を送信します](https://support.microsoft.com/supportrequestform/2afa6f15-b710-db46-909a-8346017c802f)。 その他のすべての国については、サポート Web [フォームを送信します](/licensing/contact-us)。 \n\nMAK ライセンス認証の制限を要求するには、VLSC 管理者、キー管理者、またはキー ビューアーのアクセス許可を持ち、次の情報を提供する必要があります。\n\n  - 契約/登録番号またはライセンス ID と承認。\n  - 製品名 (バージョンとエディションを含む)。\n  - プロダクト キーの最後の 5 文字。\n  - 必要なホストライセンス認証の数。\n  - ビジネスの正当性または展開の理由。\n"
  - question: >
      複数のライセンス認証キー (MAK) を使用してライセンスをアクティブ化する方法
    answer: >
      MAK を使用してライセンスをアクティブ化するには、次の 2 つの方法のいずれかを使用します。

        - MAK 独立ライセンス認証 各コンピューターは、Web または電話を使用して Microsoft に個別に接続してライセンス認証を完了します。
        - MAK プロキシライセンス認証 Microsoft にオンラインまたは電話で 1 つの接続を持つ複数のコンピューターに代わって 1 つの集中ライセンス認証要求が行います。 このメソッドは、ボリューム ライセンス認証管理ツール (VAMT) を使用します。このメソッドは、WINDOWS自動インストール キット (WAIK) の一部です。 VAMT IT プロフェッショナルは、MAK を使用してボリューム ライセンス認証プロセスを自動化および一部管理し、MAK のライセンス認証の数のチェックを含む機能を提供します。
  - question: >
      (ボリューム ライセンス認証管理ツール) のVAMT?
    answer: >
      ボリューム ライセンス認証管理ツール (VAMT) は、ネットワーク管理者や他の IT 担当者が、Windows、Microsoft Office、および他の Microsoft 製品のボリュームライセンス認証プロセスと小売ライセンス認証プロセスを自動化し、一方的に管理できるツールです。 VAMTライセンス認証キー (MAK) または複数のライセンス認証キー (WINDOWS キー管理サービス) をKMS。 VAMTは、Microsoft 管理コンソール (MMC) 3.0 を必要とする標準の Microsoft 管理コンソール (MMC) スナップインです。


      詳細については、「VAMT」を参照してください。

        - [ボリューム ライセンス認証管理ツール (VAMT) テクニカル リファレンス](/windows/deployment/volume-activation/volume-activation-management-tool)
        - [[ライセンス認証の管理] ボリューム ライセンス認証管理ツール (VAMT)](/previous-versions/tn-archive/ff686876(v=technet.10))
        - ダウンロード[ボリューム ライセンス認証管理ツール (VAMT)](https://www.microsoft.com/download/details.aspx?id=11936)
  - question: >
      クライアントをアクティブ化するWindowsサーバーをKMSする方法Windows。
    answer: "ライセンス認証方法として Windows (キー管理サービス) KMSを使用して展開する場合は、次の点に注意してください。\n  \n  - Windowsサーバーは、サーバーをアクティブ化KMSホストとしてWindows。\n  - クライアント WindowsのKMSを許可する更新プログラムを取得するには、サーバー サーバー Windowsが必要です。 最新の更新プログラムについては、「[ボリューム](/deployoffice/vlactivation/configure-a-kms-host-computer-for-office)ライセンス バージョンのアクティブ化をKMSホスト コンピューターを構成する」を参照Office。 \n\nサーバーをホストとしてWindowsしているKMS、次のコマンドを実行できます。\n  \n  - ホスト コンピューター KMSサーバーにアップグレードWindowsします。\n  - コンピューターをサーバー 2003 Windowsダウングレードします。\n  - ボリューム エディションKMSコンピューターでWindowsホストを実行します。\n  - サーバー仮想マシンWindows実行します。\n"
  - question: >
      ボリューム ライセンス認証について、Office、Project、およびVisio。
    answer: >
      次のボリューム ライセンス認証の変更は、ユーザー、Office、Projectに関連Visio。
        - Office KMS Host は、任意のスイートOfficeアプリケーションをアクティブ化します。
        - ライセンス認証Office KMS使用する必要があるキーは 1 つのみです。

      ライセンス認証方法として Office (キー管理サービス) KMSを使用して展開する場合は、次の点に注意してください。
        - サーバーをホストとしてOffice KMS場合WindowsをKMSできません。
        - 更新プログラムは、クライアントのライセンス認証を許可Officeできません。

      サーバー 2008 WindowsホストとしてKMS場合は、次のKMS実行できます。
        - ホスト コンピューター KMSサーバーにアップグレードWindowsします。
        - コンピューターを以前のバージョンのサーバーにダウンWindowsします。
        - PC 上KMSホストをWindowsします。
        - 新しいバージョンWindowsサーバーでサーバー仮想マシンを実行Windowsします。
  - question: >
      サーバーとリモート デスクトップ Windows ターミナル (RDS) をアクティブ化する方法
    answer: >
      VLSC からサーバー メディアをダウンロードしたら、製品ライセンス認証ウィザードを使用してライセンス認証できます。 VLSC でボリューム ライセンス キーまたは製品セットアップ キーを見つける必要はない。 すべてのライセンス認証ウィザードの手順を完了すると、サーバーはインターネット経由で Microsoft クリアリング ハウスに接続してデータを検証するように求めるメッセージが表示されます。 または、オフライン サーバーの場合、ライセンス認証ウィザードは電話または Web ライセンス認証を提供します。


      まず、サーバーのリモート デスクトップ ライセンスの役割 **([** 管理ツール サーバー マネージャーの起動]) を割り当て、リモート デスクトップ ライセンス マネージャーから  >    >  RDS サービスをアクティブにします。 [**管理**  >  **ツールのリモート**  >  **デスクトップ サービスの開始**] を選択し、[リモート デスクトップ/ターミナル ライセンス マネージャー]**を選択します**。


      ライセンス認証中に、ライセンス プログラムと契約番号を選択する必要があります。 [オープン ライセンスのお客様] に、承認番号を入力します。 MPSA の場合は、購入アカウント番号 (MPSA 契約番号ではなく) を入力します。 CAL ライセンスの購入に使用するライセンス ID のプログラムの種類が不明な場合は **、[VLSC リレーションシップ** の概要] に移動し、[親プログラム] 列 **を参照** してください。


      ターミナル サーバーのライセンスの詳細については、「 [ターミナル サーバー のライセンス」を参照してください](/troubleshoot/windows-server/remote/terminal-server-licensing)。 リモート デスクトップ ライセンスの役割をインストールしてライセンス サーバーをアクティブ化する方法については[](/windows-server/remote/remote-desktop-services/rds-activate-license-server)、「リモート デスクトップ サービス ライセンス サーバーをアクティブ化する」および「RD ライセンス サーバーが利用できないので[、RDS](/troubleshoot/windows-server/remote/cannot-connect-rds-no-license-server)に接続できません」を参照してください。
  - question: >
      同じ所有権構造内の組織は、同じキーを使用して製品を展開できますか?
    answer: >
      ライセンスコンプライアンスとアセット管理は、キーのアクティブ化とは独立しています。 お客様は、特定のライセンス ID (契約、登録、アフィリエイト、またはライセンス) の下で提供されるキーを使用する必要があります。 親組織に個別の契約がある場合は、同じキーを使用して、親組織と子組織に製品を展開できます。 この柔軟性により、お客様は契約/ライセンスに固有のキーを使用するか、すべてのユーザーに対して 1 セットのキーを使用して展開イメージを一中心に管理できます。
  - question: >
      ボリューム ライセンス キーを使用して再イメージング権限を行使できますか?
    answer: >
      はい。 再イメージング権限は、すべての Microsoft ボリューム ライセンスのお客様に付与されます。 これらの権利の下で、ボリューム ライセンス メディアから作成されたコピーが元のライセンス製品と同一である場合、お客様は契約に基いて提供されたメディアを使用して、元の機器メーカー (OEM) またはフル パッケージ製品 (FPP) ライセンス コピーを再イメージできます。 ボリューム ライセンスのお客様は、プロダクト キー ページでボリューム ライセンス キーを見つけるか、Microsoft ライセンス認証センターからキーを [要求できます](https://licensingapps.microsoft.com/product-activation)。


      **メモ** Open License のお客様の場合は、製品メディアへのアクセスを取得してプロダクト キーを受け取るために、イメージを変更する製品のユニットを少なくとも 1 つ購入する必要があります。


      再イメージング権限の詳細については、「製品ライセンス ブリーフ [」を参照してください](/licensing/learn-more/volume-licensing-briefs)。
  - question: >
      ローカル ファイルにキーをダウンロードする方法
    answer: "このMicrosoft 365 管理センターは、後で使用するためにプロダクト キーをローカル ファイルにダウンロードするオプションを提供します。 [ダウンロードとキー] ページからプロダクト キーをダウンロードすると、管理センター プロファイルの契約に関連付けられているすべてのボリューム ライセンス キーがファイルに含まれる。 ただし、[リレーションシップの概要] ページの [ライセンス ID] ビューからキーをダウンロードすると、表示するライセンス ID に関連付けられたキーだけがファイルに含まれる。\n\nダウンロード可能なプロダクト キー ファイルはタブ区切り形式で、Excel またはテキスト エディターで開いてキーを並べ替え、表示できます。 これらは、ファイルに含まれる列です。ライセンス **ID、****親** プログラム、**組織**、**製品**、プロダクト キー、**種類****、MAK ライセンス認証-使用済み/利用可能、シート、および OSA 状態** です。  \n\nダウンロードしたファイルをダウンロードして開Excel手順を実行します。\n  1. Microsoft Excel を開きます。\n  2. [**ファイルを**  >  **開く]** を選択し、ダウンロードした CSV ファイルを選択します。\n  3. [ **区切り]** (既定値) を選択し、[ **タブ** 区切り] を選択します (1 つの列内のすべてのデータが表示されるのを防ぐ場合)。\n  4. **[完了]** を選択します。 \n\nファイル.CSVが開き、Excel列にデータが表示されます。\n"
- name: サポート
  questions:
  - question: >
      サポートへの問い合わせ方法
    answer: >
      Microsoft 365 管理センターお客様は、電話または Web フォームでサポートに問い合わせできます。 Microsoft は 24 時間以内に Web フォームの申請に応答します。 サポートに問い合わせするには、「お問い [合わせ」をご覧ください](/licensing/contact-us)。
additionalContent: "\n## <a name=\"additional-resources\"></a>その他のリソース\n\n- [ダウンロードに関する FAQ](downloads-faq.yml)\n\n- [Open プログラムのオンライン サービスのアクティブ化に関する FAQ](online-service-activation-faq.yml)"
